### ISSUE TITLE
Recognition of integers/floats

### ISSUE THREAD

**Issue by Niols** [avsm/ocaml-yaml#15]
Hello there,

If I'm not mistaken, in Yaml, if something looks like an integer/float, it should be parsed as one. And if one really wants a string that looks like an integer/float, one has to quote it. Am I correct here? If so:

- `Yaml.of_string_exn "0"` should give `` `Float 0.`` and not `` `String "0"``
- ``Yaml.to_string (`String "0")`` should give `"\"0\"\n"` and not `"0\n"`
- ``Yaml.to_string (`Float 0.)`` *could* give `"0\n"` instead of `"0.\n"`

I don't know whether it's a bug or if I'm just mistaken (my apologies, in that case) and, if it's a bug, whether it's a bug in ocaml-yaml or libyaml.

**Comment by avsm** [comment]
fixed in yaml.1.0.0; thanks for the report!
