### ISSUE TITLE
null and boolean values are not parsed correctly

### ISSUE THREAD

**Issue by kit-ty-kate** [avsm/ocaml-yaml#16]
The `value` type allows `null` values, and according to YAML 1.1 specs, the format also allow null values. Same thing for booleans.

Specs for null values: http://yaml.org/type/null.html
Specs for boolean values: http://yaml.org/type/bool.html

However ocaml-yaml does not support the correctly the parsing of such values and treat them as strings. Example:
```
# Yaml.to_string_exn `Null;;
- : string = "\n"
# Yaml.of_string_exn (Yaml.to_string_exn `Null);;
- : Yaml.value = `String ""
```
```
# Yaml.to_string_exn (`Bool true);;
- : string = "true\n"
# Yaml.to_string_exn (`Bool false);;
- : string = "false\n"
# Yaml.of_string_exn (Yaml.to_string_exn (`Bool true));;
- : Yaml.value = `String "true"
# Yaml.of_string_exn (Yaml.to_string_exn (`Bool false));;
- : Yaml.value = `String "false"
```
This is not correct for floats (see https://github.com/avsm/ocaml-yaml/issues/15)

**Comment by avsm** [comment]
fixed in yaml.1.0.0; thanks for the report!
