### ISSUE TITLE
Quoted strings and integers/float/null/bool parsing

### ISSUE THREAD

**Issue by kit-ty-kate** [avsm/ocaml-yaml#20]
ocaml-yaml 1.0.0 "adds supports" for float, null and bool values. However there is no internal distinctions between plain strings and quoted strings and this give wrong results. For example:
```
# Yaml.of_string "'null'";;
- : Yaml.value Yaml.res = Result.Ok `Null
# Yaml.of_string "'1'";;
- : Yaml.value Yaml.res = Result.Ok (`Float 1.)
# Yaml.of_string "'true'";;
- : Yaml.value Yaml.res = Result.Ok (`Bool true)
```
Those will of course return non-symmetric values when casted into strings using `Yaml.to_string` and will make something like `"null" == null` or `'true' == true`.

**Comment by avsm** [comment]
Thanks, patches for this welcome.  In particular, what does the spec say about how this should behave?  Is the interaction between the implicit quoting well defined?
