### ISSUE TITLE
Add integers values

### ISSUE THREAD

**Issue by kit-ty-kate** [avsm/ocaml-yaml#21]
This issue is a follow-up of #15 that shouldn't have been closed I think. Only part of the issue was (partly, see #20) fixed.
There is still no distinctions between integer and float values. There should be an `Int` value, there is no way of currently writing the value `1` in yaml with ocaml-yaml except by using `String` but this is wrong (see #20)

**Comment by avsm** [comment]
Thanks for the report -- any chance of a PR for this?

**Comment by avsm** [comment]
It looks like this requires handling the tags in yaml.  The spec says:

```
data:
    # this value is parsed as a string (it's not transformed into a DateTime)
    start_date: !!str 2002-12-14

    # this value is parsed as a float number (it will be 3.0 instead of 3)
    price: !!float 3

    # this value is parsed as binary data encoded in base64
    picture: !!binary |
        R0lGODlhDAAMAIQAAP//9/X
        17unp5WZmZgAAAOfn515eXv
        Pz7Y6OjuDg4J+fn5OTk6enp
        56enmleECcgggoBADs=
```

So we need to intercept those `!!str` specifiers and use them as another source of override as well.

**Comment by kit-ty-kate** [comment]
mmh i don't think this requires handling the tags, they are a separate issues.
By default, types in yaml are inferred.

**Comment by kit-ty-kate** [comment]
The only problem with this issue is that it requires the `Yaml.value` type to not be compatible with `Ezjsonm.t` as it is currently.

**Comment by avsm** [comment]
The issue here is that JSON does not distinguish between integers and floats, and so the Ezjsonm representation will always be a float.

However, with Yaml you can always do the Yaml.yaml parse:

```
Yaml.yaml_of_string "foo: 1";;
- : Yaml.yaml Yaml.res =
Result.Ok
 (`O
    {Yaml.m_anchor = None; m_tag = None; m_implicit = true;
     m_members =
      [(`Scalar
          {Yaml.anchor = None; tag = None; value = "foo";
           plain_implicit = true; quoted_implicit = false; style = `Plain},
        `Scalar
          {Yaml.anchor = None; tag = None; value = "1"; plain_implicit = true;
           quoted_implicit = false; style = `Plain})]})
```

This preserves the value as a Yaml scalar. It's only in the translation to the JSON representation that we convert to a float. So, hopefully that's enough. Please do reopen if there's an idea of how to preserve the JSON compatibility (which is important) and distinguish floats/ints.
