### ISSUE TITLE
Random "Error calling parser"

### ISSUE THREAD

**Issue by marcinkoziej** [avsm/ocaml-yaml#33]
The call `Yaml_unix.of_file` and `Yaml.of_string` fail randomly with `error calling parser: 0`.

Version 2.0.1

How to reproduce:
1. Download this test.yaml file: https://gist.github.com/marcinkoziej/8a41897a51ee1a0f0c54ed708dbc9b05
2. Open utop in the same directory
3. Type `#request "yaml.unix";;`
4. Type `match  (Fpath.of_string "test.yaml") with | Result.Ok fp  -> Yaml_unix.of_file fp ;;` several times.

Sometimes the function will returne Result.Ok(Yaml.value) tree, and sometimes an error:
```
utop # match  (Fpath.of_string "test.yaml") with | Result.Ok fp  -> Yaml_unix.of_file fp ;;
Characters 0-81:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
Error _
Characters 0-81:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
Error _
- : (Yaml.value, Rresult.R.msg) result =
Result.Error (`Msg "error calling parser: 0")
```

**Comment by marcinkoziej** [comment]
Same bahaviour can be experienced when using `Yaml.of_string` directly

**Comment by marcinkoziej** [comment]
I can see this is same as #17 but maybe this test.yaml will be usefull (also Kubernetes related yaml :P)

**Comment by avsm** [comment]
Can you still reproduce this with v2.1.0?

**Comment by avsm** [comment]
Was fixed in https://github.com/avsm/ocaml-yaml/pull/35
