### ISSUE TITLE
Provide useful functions in a Util module 

### ISSUE THREAD

**Issue by patricoferris** [avsm/ocaml-yaml#40]
### Problem

As @avsm pointed out in [this discuss post](https://discuss.ocaml.org/t/ocaml-yaml-extracting-value-using-a-key/6396/8), and thanks to @kyp0717 for initiating the discussion, real world Yaml seems to be primarily about encoding the JSON subset rather than the more complex features the Yaml spec can encode i.e. using the `Yaml.value` type.

As such, whilst ocaml-yaml serves those who wish to use complex Yaml files, some simple utility functions for those using the `Yaml.value` type are missing and would be useful for those wishing to use the library. This issue proposes adding a `Yaml.Util` module providing basic combinators for working with the `Yaml.value` type. 

### Examples  

A lot of inspiration can be taken from the excellent `Yojson.Basic.Util` module. Some simple functions that would be good would be: 

```ocaml
val keys : value -> string list res 
(** [keys yml] returns the keys of an object *)

val values : value -> value list res 
(** [values yml] will return a list of all values stored in a list-like value  *)

val member : string -> value -> value res
(** [member key d] returns the value wrapped in [Ok] associated with [key] otherwise [Error _] *) 

val map : (value -> value) -> value -> value res 
(** [map f v] applies [f] to each element of [v] *)

(* "Unboxing" functions *)
val to_string : value -> string res 
val to_float : value -> float res
val to_bool : value -> bool res 
```

These can then be combined using the `Rresult` library that Yaml already uses. For example:

```ocaml
let () =
  let open Rresult in
  let yml = Yaml.of_string "hello: world" in
  yml >>= member "hello" >>= to_string
  |> R.pp ~ok:Format.pp_print_string ~error:R.pp_msg Format.std_formatter
(* Prints "world" *)
```

**Comment by avsm** [comment]
Commented on #43, but I'm not entirely sure why this should be in a Util module, unless we have a signature and more than one use of that collection of functions. My preference is to just have it all in Yaml.
