### ISSUE TITLE
More examples of usage?

### ISSUE THREAD

**Issue by yoanncouillec** [avsm/ocaml-yaml#5]
Is it possible to have detailed examples of usage?
With the current repl examples and the documentation it is hardly understandable how to use the library.

**Comment by avsm** [comment]
Feel free to open up a more specific request for help with what you're trying to accomplish, and I'll try to help.  I can't just write a whole book on yaml without knowing what you don't understand...

**Comment by yoanncouillec** [comment]
Hello avsm ! Thanks for your answer !

So actually, I try to load a YAML file and then to access the information from it. 
It looks somehow like:
```
port: 8080
loglevel: INFO
```
In a very basic usage of the YAML library I wonder how to:
- load a YAML file into memory ?
- access a specific field from the loaded YAML ?

Thanks a lot :)

Yoann
